FROM arm32v6/nginx:1.15.9-alpine
COPY nginx /etc/init.d/nginx

RUN chmod 755 /etc/init.d/nginx; \
    apk update; \
    apk add openrc; \
    rc-update add nginx default

COPY dist /usr/share/nginx/html

